image: alpine

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - apk update && apk add rsync
    - rsync --delete -r public/ ~/public/
  artifacts:
    paths:
      - public
  only:
    - master
