pages:
  stage: deploy
  tags:
    - shell
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - rsync --delete -r public/* /var/www/html/kehei.de/
  artifacts:
    paths:
      - public
  only:
    - master
