name: deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - run: bundle install
      - run: bundle exec htmlproofer $GITHUB_WORKSPACE/index.html
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: >
          rsync -rq --links --delete --exclude=".*"
          --exclude="Gemfile*" --exclude="deploy_key*"
          . ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
        working-directory: $GITHUB_WORKSPACE
